# Use the AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.12

# Install the Python dependencies
# Copy the requirements file into the image
COPY requirements.txt ./

# Install the dependencies
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

# Copy the source code into the image
COPY lambda_function.py ./

# Set the command to run the Lambda function
CMD ["lambda_function.lambda_handler"]